sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
env:
  - TERM=dumb
os:
  - linux
script:
  - $CXX --version
  - ./gradlew runGhLibDesktopTestGoogleTestExe
