language: cpp

compiler:
    - gcc

os:
    - linux

env:
    - TERM=dumb

script:
    - ./gradlew runGhLibDesktopTestGoogleTestExe

before_install:
    - "if [ $(uname) = Linux ]; then sudo travis/setup-linux.sh; fi"
